### ISSUE TITLE
Добавить zen-профиль на Encounter 

### ISSUE THREAD

**Issue by OlegPenzin** [fhir-ru/core#113]
Есть страница с описанием требований к ресурсу Encounter для указание диагноза в рамках случая мед.помощи
http://fhir-ru.zendoc.me/diag.DsEncounter

Необходимо добавить виджет Profile с подразделами Differential / Snapshot, основываясь на ограничениях, описанных пока в гугл-таблице [лист Encounter (Случай МП с клиническим диагнозом)]
https://docs.google.com/spreadsheets/d/1WDC22c-qnWYEJZmdKcfuIqz_OvZaC_z4b5Vg5R5YSnI/edit#gid=371194862

**Comment by Semalexa** [comment]
Профиль добавили


![2022-05-31_06-01_57](https://user-images.githubusercontent.com/345535/171158991-97ccae70-ff6a-4de4-8814-d6269cc87987.png)
