### ISSUE TITLE
Сделать маппинг ДУЛ 

### ISSUE THREAD

**Issue by eugenekogan-spb** [fhir-ru/core#116]
Маппинг значений справочника «Документы, удостоверяющие личность» НСИ ЕГИСЗ на коды FHIR для Identifier.Type

**Comment by Semalexa** [comment]
Done

http://fhir-ru.zendoc.me/valuesets.vs-identification-documents#:elements.identifier.type.mapping

![2022-05-31_06-05_32](https://user-images.githubusercontent.com/345535/171159661-d040c974-a0c6-48f9-a078-0481b68e0d2b.png)
