### ISSUE TITLE
(Дубль) Закодировать в Zen профиль Encounter

### ISSUE THREAD

**Issue by eugenekogan-spb** [fhir-ru/core#118]
Подробности опишет О.Пензин

**Comment by OlegPenzin** [comment]
коллеги, чуть раньше добавил https://github.com/fhir-ru/core/issues/113 - Добавить zen-профиль на Encounter

**Comment by eugenekogan-spb** [comment]
Прошу пардону, не заметил. Теперь их надо добавлять в проект RuCore, в колонку ToDo.
113 добавил в проект, эту архивирую.
