### ISSUE TITLE
Пол пациента

### ISSUE THREAD

**Issue by niquola** [fhir-ru/core#12]

**Comment by Albion180** [comment]
В РЭМД используется справочник 1.2.643.5.1.13.13.11.1040 Пол пациента, который отличается от варианта FHIR. Ориентироваться надо на отечественный справочник, хотя FHIR настаивает на обратном.

**Comment by alexander-ivanov** [comment]
Общероссийский профиль я думаю мы можем не ограничивать. Для РЭМД мы можем взять подмножество справочника из FHIR и сделать маппинг на http://nsi.rosminzdrav.ru/#!/refbook/1.2.643.5.1.13.13.11.1040 , это оставит наши ресурсы валидными и с точки зрения FHIR и с точки зрения требований РЭМД.

**Comment by vadi2** [comment]
Маппинг с помощью расширения?

**Comment by shamilnn** [comment]
С полом пациента вероятно два issues, а не одно:
1. Отдельный профиль для РЭМД поверх общероссийского профиля с указанием, что other и unknown считаются как unknown.
2. Трансгедеры и прочие подобные случаи – определиться, что относится к клиническим, а что к демографическим данным пациента и нужны ли они. В FHIR Patient есть глава 8.1.7 с описание этого.

**Comment by niquola** [comment]
По моему они одинаковые :)

**Comment by niquola** [comment]
@Albion180 мы можем добавить в РЭМД - unknown?

**Comment by Albion180** [comment]
> 
> 
> @Albion180 мы можем добавить в РЭМД - unknown?

Вопрос добавления новых значений не очень простой. Справочник используется во многих МИС и необходимость такого добавления должна быть обоснована. Вся система государственной статистики построена только на двух вариантах М и Ж. Даже с вариантом "неопределенный" были проблемы, когда М+Ж оказалось меньше, чем количество пациентов. Можно попробовать внести изменения под эгидой перехода на МКБ 11. Надо посмотреть, какой справочник пола используется там.

**Comment by Semalexa** [comment]
# Резюмируем предложенные варианты:

1. Общероссийский профиль не ограничивать. 
2. Для РЭМД взять подмножество справочника из FHIR и сделать маппинг на http://nsi.rosminzdrav.ru/#!/refbook/1.2.643.5.1.13.13.11.1040
3. Отдельный профиль для РЭМД поверх общероссийского профиля с указанием, что other и unknown считаются как unknown (или как other?)
4. Трансгедеры и прочие подобные случаи – определиться, что относится к клиническим, а что к демографическим данным пациента и нужны ли они. В FHIR Patient есть глава 8.1.7 с описание этого.
5. Можно попробовать внести изменения в РЭМД и добавить unknown  под эгидой перехода на МКБ 11. Надо посмотреть, какой справочник пола используется там.


## Предложение по маппингу 1.2.643.5.1.13.13.11.1040 на http://hl7.org/fhir/valueset-administrative-gender.html:

Код | Полное название | Code | Display | Definition
-- | -- | -- | -- | --
| 1 | Мужской |  male | Male | Male.
| 2 | Женский |  female | Female | Female.
 | 3 | Неопределенный|other | Other | Other.
|||unknown | Unknown | Unknown.

### Справочник https://nsi.rosminzdrav.ru/#!/refbook/1.2.643.5.1.13.13.11.1040

Код | Полное название 
-- | -- | 
| 1 | Мужской |  
| 2 | Женский |  
 | 3 | Неопределенный|

### Справочник http://hl7.org/fhir/valueset-administrative-gender.html

Code | Display | Definition
-- | -- | --
male | Male | Male.
female | Female | Female.
other | Other | Other.
unknown | Unknown | Unknown.

### Примеры маппинга v2 и v3:

#### http://hl7.org/fhir/cm-administrative-gender-v2.html

Source Concept Details | Equivalence | Destination Concept Details
-- | -- | --
Code from AdministrativeGender |   | Code from v2 SEX
male (Male) | equal | M (Male)
female (Female) | equal | F (Female)
other (Other) | wider | A (Ambiguous)
  | wider | O (Other)
unknown (Unknown) | equal | U (Unknown)

#### http://hl7.org/fhir/cm-administrative-gender-v3.html

Source Code | Equivalence | Destination Code
-- | -- | --
male | equal | M (Male)
female | equal | F (Female)
other | wider | UN (Undifferentiated)
unknown | equal | UNK

**Comment by Albion180** [comment]
Проблема не в маппинге, а в том, что мы не можем опираться на справочник FHIR в РЭМД. Возможно, есть обходные варианты аналогично CDA, в которой можно кодировать одно и то же понятие с помощью разных справочников.

**Comment by Albion180** [comment]
Другим решением может быть добавление международных вариантов кодирования в справочник https://nsi.rosminzdrav.ru/#!/refbook/1.2.643.5.1.13.13.11.1040
Но ссылка в документе, в любом случае, должна быть на этот справочник.

**Comment by Semalexa** [comment]
# Решение №1

- Общероссийский профиль не ограничивать, использовать справочник FHIR.
- В профиле РЭМД ввести расширение для указания пола пациента из федерального справочника.

**Comment by Semalexa** [comment]
# Решение №2

- Добавление международных вариантов кодирования в федеральный справочник https://nsi.rosminzdrav.ru/#!/refbook/1.2.643.5.1.13.13.11.1040

**Comment by alexander-ivanov** [comment]
Для решения №1 предлагаю использовать простое расширение (нужно уточнить url расширения)

Пример:

```json
{
  "resourceType": "Patient",
  "gender": "male",
  "extension": [
    {
      "url": "https://fhir-ru.github.io/core/StructureDefinition/patient-ramd-gender",
      "valueCodeableConcept": {
        "coding": [
          {
            "system": "https://nsi.rosminzdrav.ru/#!/refbook/1.2.643.5.1.13.13.11.1040",
            "code": "1"
          }
        ],
        "text": "Мужской"
      }
    }
  ]
}
```

При таком подходе мы следуем спецификации, и добавляем вариант дополнительного кодирования как предлагал @Albion180 

В решении №2 у нас может быть две задачи: оставить только один тип кодирования (fhir) или привести справочники к общему числу элементов:

1. Оставить только один тип кодирования требует _заменить_ текущие коды, а это сломает обратную совместимость. 
1. Привести справочники требует добавить понятие (other). Так мы получим два справочника с разными кодами, но однозначным маппингом.

Мне кажется, что "Неопределенный" из справочника РЭМД ближе к unknown, чем к other. @Albion180 @Semalexa ?

**Comment by Semalexa** [comment]
Мне кажется, что unknown больше похож на nullflavor.
Выше я приводила примеры маппинга v2 и v3, там «неопределенный» маппится на other.

Какой смысл вложен в значение «Неопределенный» в справочнике НСИ? В каких сценариях он применяется?

Например новорожденному с отклонениями невозможно определить пол, какое значение указывать? Поступил пациент без сознания, трудно определить пол, что указывать? 

Также можно ограничить в РЭМД-профиле FHIR-список значений до трёх.

**Comment by shamilnn** [comment]
Давайте я сделаю вид, что ни чего не понимаю и спрошу простой вопрос - а в чём проблема замаппить меньший value set от РЭМД на больший AdministrativeGender? 

Например, male (FHIR) - это 1 (РЭМД),  female (FHIR) - это 2 (РЭМД). Любое другое значение в поле Patient.gender, а также отсутствие этого опционального элемента, это 3 (РЭМД).

**Comment by Semalexa** [comment]
# Решение №1 с расширением

- Общероссийский профиль не ограничивать, использовать справочник FHIR.
- В профиле РЭМД ввести расширение для указания пола пациента из федерального справочника.

Пример:

```
resourceType: Patient
gender: male
extension:
- url: urn:extension:remd-patient-gender
  valueCoding:
    system: https://nsi.rosminzdrav.ru/#!/refbook/1.2.643.5.1.13.13.11.1040
    code: "1"
    display: Мужской
```

**Comment by Semalexa** [comment]
@Albion180  Осталось уточнить маппинг для Other и Unknown на справочник РЭМД.

**Comment by Semalexa** [comment]
# Принятое решение №1 с расширением

- Общероссийский профиль не ограничивать, использовать справочник FHIR.
- В профиле РЭМД ввести расширение для указания пола пациента из федерального справочника.

Пример:

```
resourceType: Patient
gender: male
extension:
- url: urn:extension:remd-patient-gender
  valueCoding:
    system: https://nsi.rosminzdrav.ru/#!/refbook/1.2.643.5.1.13.13.11.1040
    code: "1"
    display: Мужской
```

## Маппинг фед. справочника 1.2.643.5.1.13.13.11.1040 на FHIR http://hl7.org/fhir/valueset-administrative-gender.html:

FHIR Code | Display | Definition|REMD Код | Полное название|
-- | -- | -- | -- | --|
 |  male | Male | Male.| 1 | Мужской|
 |  female | Female | Female.| 2 | Женский|
|other | Other | Other. | 3| Неопределенный 
|unknown | Unknown | Unknown.| null |null

где null - это поле отсутствует в данных.
