### ISSUE TITLE
Дата рождения

### ISSUE THREAD

**Issue by Albion180** [fhir-ru/core#13]
Дата рождения может быть не известна полностью. Нужно предусмотреть варианты как неполной информации: известен только год или год и месяц. Так и более точной информации: год, месяц, день, час, минута. Это бывает важно для новорожденных.

**Comment by alexander-ivanov** [comment]
В базовой версии дата рождения имеет тип date (The format is YYYY, YYYY-MM, or YYYY-MM-DD).
Для новорожденных можно использовать базовое расширение (часто используемые поля, которые при этом не достаточно общие, для включения в сам ресурс) - https://www.hl7.org/fhir/extension-patient-birthtime.html

**Comment by Albion180** [comment]
> 
> 
> В базовой версии дата рождения имеет тип date (The format is YYYY, YYYY-MM, or YYYY-MM-DD).
> Для новорожденных можно использовать базовое расширение (часто используемые поля, которые при этом не достаточно общие, для включения в сам ресурс) - https://www.hl7.org/fhir/extension-patient-birthtime.html

Решения возможны разные, но они должны быть. Нужно договориться, как это правильно сделать.

**Comment by shamilnn** [comment]
Пример extension, который можно в явно виде включить в текстовое описание или в пример ресурса:
`
 {
  "birthDate":"2016-05-18",
  "_birthDate":{
    "extension":[{
      "valueDateTime":"2016-05-18T10:28:45Z"
     }]
  }
 }
`
В самом extension должно быть описано, нужен ли time zone в явном виде и в каких случаях. 
Например, если ребёнок родился в 00:05 в одном часовом поясе, а система находится в другом часовом поясе (на час позже), будет ли подобное сообщение отброшено потому что дата рождения в будущем относительно системы?

**Comment by niquola** [comment]
> Пример extension, который можно в явно виде включить в текстовое описание или в пример ресурса:
> 
> ```
>  {
>   "birthDate":"2016-05-18",
>   "_birthDate":{
>     "extension":[{
>       "valueDateTime":"2016-05-18T10:28:45Z"
>      }]
>   }
>  }
> ```
> 
> В самом extension должно быть описано, нужен ли time zone в явном виде и в каких случаях.
> Например, если ребёнок родился в 00:05 в одном часовом поясе, а система находится в другом часовом поясе (на час позже), будет ли подобное сообщение отброшено потому что дата рождения в будущем относительно системы?

я категорически против расширений для примитивной - это серьезная дизайн ошибка в fhir. Мы можем просто добавить bithDateTime extension в пациента, достигнув той же цели

**Comment by shamilnn** [comment]
> я категорически против расширений для примитивной - это серьезная дизайн ошибка в fhir. Мы можем просто добавить bithDateTime extension в пациента, достигнув той же цели

Как-нибудь на стриме объясни почему.

Если просто extension, то можно взять уже существующий - http://hl7.org/fhir/StructureDefinition/patient-birthTime
Особенность этого extension, что "_If hours and minutes are specified, a time zone SHALL be populated._"

**Comment by Semalexa** [comment]
# Решение 1

- Использовать Patient.birthDate для указания даты рождения пациента. Тип данных у этого поля date, что позволяет задать полную или частичную дату (год; год и месяц; год, месяц и число)
- Ввести новое расширение Patient.birthDateTime с типом данных dateTime и указывать дату и время рождения полностью, когда это необходимо
- Стандартное расширение http://hl7.org/fhir/extension-patient-birthtime.html расширяет примитивный элемент Patient.birthDate, что нежелательно

**Comment by Semalexa** [comment]
# Решение 2

- Использовать Patient.birthDate для указания даты рождения пациента. Тип данных у этого поля date, что позволяет задать полную или частичную дату (год; год и месяц; год, месяц и число)
- Ввести новое расширение Patient.birthTime с типом данных time

**Comment by Semalexa** [comment]
# Решение 1 принято

- Использовать Patient.birthDate для указания даты рождения пациента. Тип данных у этого поля date, что позволяет задать полную или частичную дату (год; год и месяц; год, месяц и число)
- Ввести новое расширение Patient.birthDateTime с типом данных dateTime и указывать дату и время рождения полностью, когда это необходимо

Ссылка на профиль: https://fhir-ru.github.io/core/profiles/Patient/ru.html

**Comment by vadi2** [comment]
Новое расширение не нужно, стандартное уже есть - https://www.hl7.org/fhir/extension-patient-birthtime.html

**Comment by Semalexa** [comment]
> Новое расширение не нужно, стандартное уже есть - https://www.hl7.org/fhir/extension-patient-birthtime.html

Стандартное расширение http://hl7.org/fhir/extension-patient-birthtime.html расширяет примитивный элемент Patient.birthDate, чего мы хотели бы избежать.
