### ISSUE TITLE
Кодирование Practitioner

### ISSUE THREAD

**Issue by Semalexa** [fhir-ru/core#17]
https://fhir-ru.github.io/core/profiles/Practitioner/remd.html

![20200311-065850-685](https://user-images.githubusercontent.com/345535/76414660-c5d2e180-6365-11ea-96e2-5d6ba10fb1e0.png)

**Comment by shamilnn** [comment]
Вопрос - Practitioner ресурс для "обычного" использования (например, Patient.generalPractitioner) и для Practitioner Registry - это один и тот же ресурс или разные? В зависимости от этого может быть один или два профайла для Practitioner.

Practitioner.name - кодирование вероятно такое же как Patient.name, т.е. Cardinality [0..*], Must Support и все те же Slice.

Practitioner.identifier - Cardinality [0..*], Must Support
Может использовать все те же идентификаторы как Patient.identifier и вероятно может дублировать Practitioner.qualification (например, номер диплома вполне уникальный идентификтор).

Practitioner.qualification - возможно нужен отдельный issue для обсуждения только этого элемента.

Extensions:
Practitioner.deceased - Cardinality [0..*], Must Support, ModifierExtension - если ведущий врач умер, клинические процессы могут сильно измениться.

**Comment by alexander-ivanov** [comment]
По ссылке у нас профиль РЭМД. Этот профиль больше похож на профиль для реестра. В нем нам необходимо довольно мало данных, которые все закодированы. 

А вот для базового профиля, который мы еще не делали, я думаю нужно учесть все вышеперечисленное.
