### ISSUE TITLE
Актуализировать шаблон/инструкцию по созданию IG

### ISSUE THREAD

**Issue by eugenekogan-spb** [fhir-ru/core#171]
http://fhir-ru.zendoc.me/ig-tpl

**Comment by OlegPenzin** [comment]
актуализируем исходя из текущих наработок  клинической группы

**Comment by Vrodvi** [comment]
Страница с шаблоном\инструкцией по созданию IG актуализирована - см. http://fhir-ru.zendoc.me/ig-tpl
Страница с шаблоном\инструкцией по созданию страницы профиля внутри IG создана - см. http://fhir-ru.zendoc.me/ig-tpl.ig-tpl-prfl

![image](https://user-images.githubusercontent.com/92928137/178268530-ce4ec2eb-6431-41ed-b56c-e38f9229f1ae.png)

**Comment by Vrodvi** [comment]
@OlegPenzin Олег, просьба ознакомиться и перевести в статус `Done`.
