### ISSUE TITLE
Кодирование PractitionerRole

### ISSUE THREAD

**Issue by Semalexa** [fhir-ru/core#18]
https://fhir-ru.github.io/core/profiles/PractitionerRole/remd.html

![20200311-065941-715](https://user-images.githubusercontent.com/345535/76414722-e26f1980-6365-11ea-88a1-8a7da688aaa5.png)

**Comment by shamilnn** [comment]
Extensions:
PractitionerRole.roleStatus - Cardinality [0..*], Must Support, ModifierExtension - Code representing the defined possible states of an Role, as defined by the Role class state machine. 
Binding - http://hl7.org/fhir/r4/v3/RoleStatus/vs.html

Может быть использован если, например, лицензия врача временно приостановлена. анулирована и т.п.
