### ISSUE TITLE
Предложение по замене OID на человекочитаемые названия

### ISSUE THREAD

**Issue by Semalexa** [fhir-ru/core#20]
# Предложение

Вести отдельный маппинг для OID и использовать человекочитаемые urn в качестве значения поля system.
См. https://github.com/fhir-ru/core/issues/2

Возможные примеры:

|Code  | System  |  Display |  Definition | OID |
|---|---|---|---|---|
| urn:identity:snils  | urn:CodeSystem:ru-patient-identifier  | СНИЛС  |   | 1.2.643.2.69.1.1.1.6.22.3|
| urn:identity:enp  | urn:CodeSystem:ru-patient-identifier   | ЕНП  | Единый номер полиса ОМС  |  |
| urn:identity:passport-rf  |  urn:CodeSystem:ru-patient-identifier  | Паспорт РФ  |   | 1.2.643.2.69.1.1.1.6.14 |
|  urn:identity:birth-certificate | urn:CodeSystem:ru-patient-identifier   | Свидетельство о рождении	  |   |  |
| urn:identity:insurance-gov  |  urn:CodeSystem:ru-patient-identifier  |  Страховой полис |  Полис ОМС единого образца, выданный в соответствии с требованиями Закона об ОМС |1.2.643.2.69.1.1.1.6.22.8  |
| urn:identity:insurance-gov-legacy  |  urn:CodeSystem:ru-patient-identifier  | Страховой полис старого образца  | Полис ОМС, выданный до вступления в силу Закона об ОМС (старый полис)  |1.2.643.2.69.1.1.1.6.22.6  |
| urn:identity:insurance-gov-temporary  |  urn:CodeSystem:ru-patient-identifier  | Временный страховой полис  | Временное свидетельство, подтверждающее оформление полиса ОМС  |  |
| urn:identity:dms |  urn:CodeSystem:ru-patient-identifier  | ДМС |   | 1.2.643.2.69.1.1.1.6.24.0 |

_NID_ `finance` -  для околофинансовой информации

```
urn:finance:inn
urn:finance:ogrn
urn:finance:bic
```

_NID_ `miac` -  для регионального МИАЦ 

```
urn:miac:spb
urn:miac:mo
urn:miac:chu
```

_NID_ `source` -  для локального использования (интеграция) и идентификации источника, откуда пришли данные.

```
urn:source:tfoms
urn:source:miac
urn:source:rmis-1
urn:source:mis-3
```

## Пример с использованием OID (Нетрика)

```
"identifier": [
    {
      "system": "urn:oid:1.2.643.2.69.1.1.1.6.228",
      "value": "1234567812345678",
      "use": "temp",
      "period": {
        "start": "2010-05-05"
      },
      "assigner": {
        "display": "1.2.643.5.1.13.2.1.1.635.22001"
      }
    },
    {
      "system": "urn:oid:1.2.643.5.1.13.2.7.100.5",
      "value": "527589409846325",
      "assigner": {
        "display": "1.2.643.2.69.1.2.6"
      }
    },
    {
      "system": "urn:oid:1.2.643.2.69.1.1.1.6.14",
      "value": "1045:348707",
      "period": {
        "start": "2010-05-05"
      },
      "assigner": {
        "display": "УФМС по РФ в г. Петрозаводск"
      }
    },
    {
      "system": "urn:oid:1.2.643.2.69.1.1.1.6.223",
      "value": "12345678901",
      "assigner": {
        "display": "ПФР"
      }
    },
    {
      "system": "urn:oid:1.2.643.2.69.1.1.1.6.240",
      "value": "2342ll:123",
      "assigner": {
        "display": "ДМС"
      }
    }
  ]
```

## Правила для указания identifier.system (Нетрика)

Пространство имён идентификатора. Указывается код:
• для идентификатора в МИС/ЛИС OID (1.2.643.5.1.13.2.7.100.5), 
• для идентификатора прикрепления  OID (1.2.643.5.1.13.2.7.100.9),
для ДУЛ и полисов OID (1.2.643.2.69.1.1.1.6.Х), где Х = код документа в справочнике 1.2.643.2.69.1.1.1.6. Для ДУЛ допустимые значения (1-18),  для СНИЛС 223, для полисов ОМС (226-228),  для полисов ДМС 240.

**Comment by Semalexa** [comment]
Пример маппинга из Чувашии https://fhir-ru.github.io/core/valuesets/chu-federal-oid.html

**Comment by alexander-ivanov** [comment]
Мне кажется uri более читаемые чем oid. Мы используем url для кодирования систем, но у них есть два недостатка:

* Большая часть url не несет полезной нагрузки (например, ```http://example.org/identity/snils```, все до identity не нужно.)
* С url мы регулярно видим проблему http/https, у разных кодовых систем используются разные схемы 

Кажется, что urn часть этих проблем решает. Поэтому я за, думаю мы готовы у себя перейти на urn.
