### ISSUE TITLE
Заголовок CDA РЭМД в FHIR

### ISSUE THREAD

**Issue by alexander-ivanov** [fhir-ru/core#21]
Ссылка на описание [РЭМД](https://docs.google.com/spreadsheets/d/1G0u8uIoHD3OmmANxN1MYOHYDhk6riSwe4gSj0OaH6BE/edit#gid=870669113)

Ссылка на предложение по кодированию [заголовка в FHIR](https://docs.google.com/spreadsheets/d/1zkzeId_WUfDTcdJo8Iqjahc24yuzz149CZrNDz4Bfgo/edit?usp=sharing)

Мы хотели каждый вопрос вынести отдельно, но мне кажется, что многие из них мы можем быстро решить, поэтому предлагаю начать тут, а затем проблемные вопросы выносить.

Вопросы:
1. В FHIR информация из заголовка CDA может попадать в два места - внутренний заголовок документа (ресурс [Composition](https://www.hl7.org/fhir/composition.html) и внешнее описание документа (ресурс [DocumentReference](https://www.hl7.org/fhir/documentreference.html)). Рассматриваем ли мы оба или концентрируемся на Composition?
1. Поле "Область применения документа (Страна)" из CDA - Прямого аналога нет, обычно для этого есть поле jurisdiction (пример в PlanDefinition), можно сделать экстеншн? 
1. Поле "Указатель на использование CDA R2" - нам хорошо бы тоже знать версию FHIR документа. Возможно, это более инфраструктурный вопрос - будет ли поддержка разных версий? Будет ли полноценный XDS для РЭМД? Вариант: закодировать в DocumentReference-> Attachment -> ContentType 
1. Поле "Идентификатор Шаблона документа "Протокол лабораторного исследования. Третий уровень формализации." по справочнику "Справочник шаблонов CDA документов"". Мы можем в метаинформацию документа записать, что он соответствует профилю РЭМД. Будет ли этого достаточно?
1. Поле "Уникальный идентификатор набора версий документа" - в DocumentReference есть "Master Version Specific Identifier", в Composition - "Version-independent identifier for the Composition". Используем их или нужны расширения?
1. Поле "Номер версии данного документа" - не знаю куда писать эту информацию.

@Semalexa можешь прислать ссылку на конвертер CDA в FHIR?

**Comment by Semalexa** [comment]
@alexander-ivanov  Конвертер CDA в FHIR https://github.com/ahdis/cda-core-2.0/releases/tag/v0.0.2-dev, должна быть и более свежая версия.

Пример результата конвертации:

https://fhir-ru.github.io/core/profiles/Bundle/remd.html - Examples

[SampleCDA.zip](https://github.com/fhir-ru/core/files/4379974/SampleCDA.zip) - файл SampleCDADocumentRuProtocolOfLabObservation_max-fhir.yaml

Профили на Bundle и Composition:
https://fhir-ru.github.io/core/profiles/Bundle/remd.html
https://fhir-ru.github.io/core/profiles/Composition/remd.html
