### ISSUE TITLE
Кодирование микробиологических результатов

### ISSUE THREAD

**Issue by Semalexa** [fhir-ru/core#22]
Пример данных:
![20200325-062457-821](https://user-images.githubusercontent.com/345535/77531939-d012d680-6e61-11ea-9d98-5e4abf461982.png)

Схема кодирования на ресурсы DiagnosticReport и Observation:

![Labs Terminology-Micro (1)](https://user-images.githubusercontent.com/345535/77534100-123e1700-6e66-11ea-90e2-c5e7445d0089.png)

**Comment by alexander-ivanov** [comment]
Доп инфо: [этой доке](https://www.hl7.org/fhir/diagnosticreport-examples.html) есть описание как fhir предлагает кодировать микробиологию.

**Comment by Semalexa** [comment]
Вариант кодирования по примеру из доки Промежуточный вариант отображения СЭМД при передаче результатов микробиологического исследования (https://docs.google.com/spreadsheets/d/11ir5pRCBIQeM9a4sim8Wskbq3m21AVM_ghg81k-cPzc/edit?usp=sharing)

![Tasks Workflow-Micro (СЭМД)](https://user-images.githubusercontent.com/345535/80213495-e053d800-85fe-11ea-92eb-b5369d293545.png)

![20200424-074116-066](https://user-images.githubusercontent.com/345535/80213612-0c6f5900-85ff-11ea-95d8-4c59969ddaad.png)

**Comment by Semalexa** [comment]
Рабочий процесс выполнения направления на микробиологическое исследование, разбитый на подзадачи:

![Tasks Workflow-Micro Workflow](https://user-images.githubusercontent.com/345535/80213672-2446dd00-85ff-11ea-9b68-38013a172681.png)
