### ISSUE TITLE
Схема кодирования комплексной услуги, которой нет в НМУ

### ISSUE THREAD

**Issue by Semalexa** [fhir-ru/core#23]
Схема кодирования комплексной услуги, которой нет в НМУ, на примере "Определение группы крови и резус-фактора":

![Labs Terminology-Группа крови и резус](https://user-images.githubusercontent.com/345535/77534848-68f82080-6e67-11ea-8053-3ac730c21341.png)

**Comment by alexander-ivanov** [comment]
Мы сейчас используем DiagnosticReport на выполняемое исследование. Т.е. у нас похожий пример будет давать два DiagnosticReport со ссылками на общий ServiceRequest
