### ISSUE TITLE
Добавить поддержку инструментария FHIR Shorthand.

### ISSUE THREAD

**Issue by Vrodvi** [fhir-ru/core#27]
![image](https://user-images.githubusercontent.com/92928137/141097220-bca28892-2753-4b6d-a0dc-46989fa21138.png)

Предлагаю добавить в манифест, в раздел [Технологичность](https://github.com/fhir-ru/core/wiki/%D0%9C%D0%90%D0%9D%D0%98%D0%A4%D0%95%D0%A1%D0%A2-FHIR-Ru-Core#%D0%A2%D0%B5%D1%85%D0%BD%D0%BE%D0%BB%D0%BE%D0%B3%D0%B8%D1%87%D0%BD%D0%BE%D1%81%D1%82%D1%8C), поддержку официального инструментария от HL7 по работе с профилями ресурсов - [FHIR Shorthand](http://build.fhir.org/ig/HL7/fhir-shorthand/).

**Comment by niquola** [comment]
Думаешь он лучше igpop?

**Comment by Vrodvi** [comment]
> Думаешь он лучше igpop?

Как минимум, FHIR Shorthand (и SUSHI) официально поддерживается HL7 и позволяет сформировать руководство по реализации в знакомом всем кто работает с FHIR формате.

Про лучше \ не лучше - если судить по имеющейся для FHIR Shorthand документации, инструментам (SUSHI, FSH converter) и архиву с примерами, то мне кажется он доступнее для освоения.

**Comment by niquola** [comment]
Пока пробуем на zen-lang - если не получится - вернемся
