### ISSUE TITLE
Кодирование адреса проживания "по регистрации - фактическое"

### ISSUE THREAD

**Issue by MaximA10rus** [fhir-ru/core#6]
Существует необходимость раздельного указания адресов для пациента - "по регистрации" и "по фактическому проживанию". 

Предлагается использовать для указания типа адреса параметр Patient.address.use следующим образом: 

home | Home | A communication address at a home - адрес по регистрации 

temp | Temporary | A temporary address. The period can provide more detailed information. - адрес по фактическому проживанию 

Логическое обоснование:

- Patient.address.use == "home" - главный, основной, официальный адрес пациента. Плюс по российским законам гражданин "должен зарегистрироваться по месту жительства или пребывания..." и т.д. 

- Patient.address.use == "temp" - адрес фактического проживания. Подразумеваем, что прописка гражданина по адресу home, но **временно** фактически он проживает по адресу temp. 
 
Пример: 

  "address": [
        {
            "use": "home",
            "text": "СПб, ул.Оптиков, д.6, кв.101"
        },
        {
            "use": "temp",
            "text": "Спб, ул.Коллонтай, д.6, кв.101"
        }
    ]

**Comment by niquola** [comment]
Альтернатива:
про address.use имеет смысл закинуть в zulip. Думаю предпологалось что official - billing, а фактическое проживание - home

**Comment by shamilnn** [comment]
В CA Core мы используем "preferred" extension - http://hl7.org/fhir/StructureDefinition/iso21090-preferred.
Для бездомных или не имеющих адреса по другим причинам - "nofixedaddress" extension.
