### ISSUE TITLE
Передача информации о полисе - Patient.identifier или Coverage? 

### ISSUE THREAD

**Issue by MaximA10rus** [fhir-ru/core#7]
По стандарту - информацию о полисе нужно передавать в ресурсе Coverage. 
На данный момент в обсуждениях мы придерживаемся тактики передачи информации о полисе через один из Patient.identifier. 
Предлагаю обсудить оба варианта и зафиксировать здесь выбранный и причину, по которой мы решили делать именно так, а не иначе 

В большей степени нижеуказанные +/- касаются обмена между МИС/РЕГИЗ, при передаче в тот же СЭМД/РЭМД +/- нивелируются. 

Использование Patient.identifier 

(+) компактная передача данных (по полисам нам надо номер, дату этого полиса, больше по сути ничего не используется и это все можно вместить в identifier, а не городить целый ресурс)
(+) отсутствие дублирования информации о полисах 
(-) отсутствие историчности (при передаче Patient старые данные перетираются и недоступны в явном виде. Работа с history ресурса для многих сложная и неочевидная)

Использование Coverage

(+) поддержка историчности изменения полисов 
(+) возможность передачи информации по лечению, оплачиваемому по разным полисам (начали по времянке, потом дали постоянный. или - сменилась СМО. по ОМС в стационаре довольно частый случай)
(-) необходимость следить за тем, чтобы в базе не скапливалась куча одинаковых полисов (блокировка передачи полиса с одним номером, типом, СМО)
(-) передача немного сложнее

**Comment by niquola** [comment]
Думаю они не исключают друг друга - те можно использовать номер полиса как patient identifier и при этом детали моделировать как Coverage

**Comment by niquola** [comment]
Для пациента нам нужно будет внести их в VS для Patient.identifier.system - #2
